
  "/namespace-<<X>>-name",
  "/namespace-<<X>>-replication-factor",
  "/namespace-<<X>>-memory-size",
  "/namespace-<<X>>-conflict-resolution-policy",
  "/namespace-<<X>>-default-ttl",
  "/namespace-<<X>>-single-bin",
  "/namespace-<<X>>-data-in-index",	
  "/namespace-<<X>>-ldt-enabled",
  "/namespace-<<X>>-storage-engine",
  "/namespace-<<X>>-storage-engine-device",
  "/namespace-<<X>>-storage-engine-write-block-size",
  "/namespace-<<X>>-storage-engine-file",
  "/namespace-<<X>>-storage-engine-filesize",
  "/namespace-<<X>>-storage-engine-data-in-memory",
  "/namespace-<<X>>-stop-writes-pct",
  "/namespace-<<X>>-high-water-memory-pct",
  "/namespace-<<X>>-high-water-disk-pct",

